### PR TITLE
Remove DL's from portlet templates.

### PR DESCRIPTION
**Pull request by khink**
For Plone 5, don't merge unless a branch for that exists.
https://github.com/plone/Products.CMFPlone/issues/153
https://github.com/plone/Products.CMFPlone/issues/163

### CODE REVIEW

**Comment by jensens** [comment]
@khink do we still need this one?

**Comment by khink** [comment]
I'd say yes

**Comment by jensens** [comment]
Can you please rebase, so we can merge?

**Comment by jensens** [comment]
http://jenkins.plone.org/view/All/job/pull-request/24/ passes

**Pull request merged**
